general.import = [
   "~/.config/alacritty/kanagawa-wave.toml",
]
general.live_config_reload = true # set config to live reload on change

[font]  # font stuff
size = 13.0

[font.normal]
family = "Maple Mono"
style = "Medium"

[font.bold]
family = "Maple Mono"
style = "Heavy"

[font.bold_italic]
family = "Maple Mono"
style = "Heavy Italic"

[font.italic]
family = "Maple Mono"
style = "Medium Italic"

[env] # environment variables
TERM = "xterm-256color"

[window]  # transparency and stuff
# decorations = "buttonless"
dynamic_padding = false
opacity = 1

# Colors (Gruvbox dark)

# Default colors
#[colors.primary]
#background = '#181616'


## Normal colors
#[colors.normal]
#black   = '#1b1b1b'
#red     = '#cc241d'
#green   = '#98971a'
#yellow  = '#d79921'
#blue    = '#458588'
#magenta = '#b16286'
#cyan    = '#689d6a'
#white   = '#a89984'
#
## Bright colors
#[colors.bright]
#black   = '#928374'
#red     = '#fb4934'
#green   = '#b8bb26'
#yellow  = '#fabd2f'
#blue    = '#83a598'
#magenta = '#d3869b'
#cyan    = '#8ec07c'
#white   = '#ebdbb2'
