#cursor_trail 1

confirm_os_window_close -1 count-background
copy_on_select yes

enable_audio_bell no

draw_minimal_borders no
window_padding_width 0
window_border_width 0
hide_window_decorations no
active_border_color none

# Transparency
background_opacity 1
background_blur 1

# Tabs
tab_bar_edge top
tab_bar_style powerline
tab_title_template "{fmt.fg.c2c2c2}{title}"

# Font
#font_family     JetBrainsMono Nerd Font Mono
#font_family     FiraCode Nerd Font
font_family     Maple Mono Normal NF
font_size       13.0
bold_font       auto
italic_font      auto
bold_italic_font auto

# Theme (gruvbox_dark)
include config.d/gruvbox.conf
