version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
  black = '#000000'
  red = 'red'
  green = 'green'
  yellow = 'yellow'
  blue = 'blue'
  purple = 'magenta'
  cyan = 'cyan'
  white = '#eeeeee'

[palettes]
  template = '{{ if .Root }}root{{ else }}user{{end}}'
  
  [palettes.list.user]
    background = "#3c3836"
  
  [palettes.list.root]
    background = "#ff0000"

# OS icon block
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "os"
    style = "powerline"
    powerline_symbol = ''
    background = "p:background"
    foreground = "p:white"
    template = "{{.Icon}}  "

# username@host block
  [[blocks.segments]]
    type = "session"
    style = "powerline"
    powerline_symbol = ''
    background = 'p:background'
    foreground = 'green'
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }}</> <p:white> '

# path block
  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
#    style = 'diamond'
#    leading_diamond = ' '
#    trailing_diamond = ''
    foreground = "p:yellow"
    background = "p:background"
    template = " {{ .Path }}</> <p:white> "
 
    [blocks.segments.properties]
      style = 'full'

# git block
  [[blocks.segments]]
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}</> <p:white> '
#template = '{{ .HEAD }}'
    foreground = 'p:cyan'
    powerline_symbol = ''
    background = 'p:background' 
    type = 'git'
    style = 'powerline'
#foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
#background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']
    [blocks.segments.properties]
      branch_max_length = 25.0
      fetch_status = true
      fetch_upstream_icon = true

# git block number the second
  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    background = "p:background"
    foreground = "p:blue"
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }} <p:cyan>*{{ end }} {{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</> <p:white> </>'

    [blocks.segments.properties]
      commit_icon = "@"
      fetch_status = true

# time block 
  [[blocks.segments]]
    type = "time"
    style = "powerline"
    powerline_symbol = ''
    foreground = "p:purple"
    background = "p:background"
    template = " {{ .CurrentDate | date .Format}} "
    
    [blocks.segments.properties]
      time_format = "15:04"


# right hand side blocks
[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

# executiontime
  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

# second line
[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = ["{{if gt .Code 0}}red{{end}}",]
    foreground = "p:green"
    template = "❯"

[transient_prompt]
 background = "transparent"
 foreground = "p:green" 
 foreground_templates = ["{{if gt .Code 0}}red{{end}}",]
 template = "❯ "

