version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
  black = '#000000'
  red = 'red'
  green = 'green'
  yellow = 'yellow'
  blue = 'blue'
  magenta = 'magenta'
  lightMagenta = 'lightMagenta'
  cyan = 'cyan'
  white = '#eeeeee'

[palettes]
  template = '{{ if .Root }}root{{ else }}user{{end}}'
  
  [palettes.list.user]
    background = "#3c3836"
  
  [palettes.list.root]
    background = "#ff0000"

# left blocks
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

# OS icon block
  [[blocks.segments]]
    type = "os"
    style = "powerline"
    powerline_symbol = ''
    background = "p:background"
    foreground = "p:white"
    template = "{{.Icon}}  "

# username@host block
  [[blocks.segments]]
    type = "session"
    style = "powerline"
    powerline_symbol = ''
    background = 'p:background'
    foreground = 'p:green'
#    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }}</> <p:white> '
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }}</><p:blue>@</><p:red>{{ .HostName }}</> <p:white> '

# path block
  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
#    style = 'diamond'
#    leading_diamond = ' '
#    trailing_diamond = ''
    foreground = "p:yellow"
    background = "p:background"
    template = " {{ .Path }}</> <p:white> "
 
    [blocks.segments.properties]
      style = 'full'

# git block
  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    background = "p:background"
    foreground = "p:magenta"
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}<p:lightMagenta>*{{ end }} {{if .BranchStatus }} {{ .BranchStatus }} {{ end }}</> <p:white> </>'

    [blocks.segments.properties]
      commit_icon = "@"
      fetch_status = true

# time block 
  [[blocks.segments]]
    type = "time"
    style = "powerline"
    powerline_symbol = ''
    foreground = "p:cyan"
    background = "p:background"
    template = " {{ .CurrentDate | date .Format}} "
    
    [blocks.segments.properties]
      time_format = "15:04"


# right hand side blocks
[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

# executiontime block
  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

# second line
[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = ["{{if gt .Code 0}}p:red{{end}}",]
    foreground = "p:green"
    template = "❯"
#    template = "->"

[transient_prompt]
  background = "transparent"
  foreground = "p:green" 
  foreground_templates = ["{{if gt .Code 0}}p:red{{end}}",]
  template = "❯ "
#  template = "-> "
