console_title_template = '{{ if .Root }} root@{{ end }}{{ .Env.MACHINAHOSTNAME }} {{ .PWD }}'
final_space = true
version = 3

# palette for everyone except root
[palette]
  background = '#3c3836'

###############
# left blocks #
###############

# OS icon block
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'powerline'
    powerline_symbol = ''
    background = 'p:background'
    foreground = 'lightWhite'
    template = '{{.Icon}} '

# username@host block
[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    powerline_symbol = ''
    background = 'p:background'
    foreground = 'green'
    template = ' <lightWhite>{{ if .SSHSession }} {{ end }}{{ if .Root }}</><red>{{ end }}{{ .UserName }}</></><blue>@</>{{ if contains "prod" .Env.MACHINAHOSTNAME }}<red>{{ end }}{{ .Env.MACHINAHOSTNAME }} '

# path block
[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = 'yellow'
    background = 'p:background'
    template = ' {{ .Path }}</> '

# path block properties 
    [blocks.segments.properties]
      style = 'full'

# git block
[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    background = 'p:background'
    foreground = 'magenta'
    template = ' {{ .HEAD }}<lightMagenta>{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{if .BranchStatus }} {{ .BranchStatus }} {{ end }}</>'

# git block properties
    [blocks.segments.properties]
      commit_icon = '@'
      fetch_status = true

# time block 
[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'time'
    style = 'powerline'
    powerline_symbol = ''
    foreground = 'cyan'
    background = 'p:background'
    template = ' {{ .CurrentDate | date .Format}} '

# time block properties
    [blocks.segments.properties]
      time_format = '15:04'

###############
# right block #
###############

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

# executiontime block
  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    leading_diamond = ' '
    trailing_diamond = ''
    foreground = 'yellow'
    background = 'p:background'
    template = '{{ .FormattedMs }}'

# executiontime properties
    [blocks.segments.properties]
      threshold = 5000
###############
# second line #
###############

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

# Prompt
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}',]
    foreground = 'green'
    template = '{{if contains "prod" .Env.MACHINAHOSTNAME }}<red>{{ .Env.MACHINAHOSTNAME }}</> {{ end }}❯'

# Transient prompt
[transient_prompt]
  background = 'transparent'
  foreground = 'green' 
  foreground_templates = ['{{if gt .Code 0}}red{{end}}',]
  template = '❯ '
