console_title_template = "{{ if .Root }} root@{{ end }}{{ .HostName }} {{ .PWD }}"
final_space = true
version = 3
enable_cursor_positioning = true  # if you have issues with your prompt taking a while to start, disable this

# Palette
[palette]
  orange = "#d65d0e"
  cisBlack = "#1b1b1a"

# Left block
[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "os"
    template = "{{ .Icon }} "
    background = "p:cisBlack"
    foreground = "lightWhite"
    style = "diamond"
    leading_diamond = ""

## Root block
  [[blocks.segments]]
    type = "root"
    template = " sudo"
    background = "red"
    foreground = "lightWhite"
    style = "accordion"
#powerline_symbol = ""
    powerline_symbol = ""

## Username block
  [[blocks.segments]]
    type = "session"
    template = " {{ if .SSHSession }} {{ end }}{{ .UserName }}"
#background_templates = ['{{if .Root }}red{{end}}',]
    background = "p:orange"
    foreground = "black"
    style = "accordion"
#powerline_symbol = ""
    powerline_symbol = ""

## Host block
  [[blocks.segments]]
    type = "session"
    template = " {{ .HostName }}"
    background = "yellow"
    foreground = "black"
    style = "accordion"
#powerline_symbol = ""
    powerline_symbol = ""

## Path block
  [[blocks.segments]]
    type = "path"
    template = " {{ .Path}}"
    background = "green"
    foreground = "black"
    style = "accordion"
#powerline_symbol = ""
    powerline_symbol = ""
### Path block properties
    [blocks.segments.properties]
      style = "full"

## Git block
  [[blocks.segments]]
    type = "git"
    template = " {{ .HEAD }}<lightWhite>{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}</>"
    background = "blue"
    foreground = "black"
    style = "accordion"
#powerline_symbol = ""
    powerline_symbol = ""
### Git block properties
    [blocks.segments.properties]
      fetch_status = true
      #commit_icon = "@"

# Time block
  [[blocks.segments]]
    type = "time"
    template = " {{ .CurrentDate | date .Format }}"
    style = "accordion"
#powerline_symbol = ""
    powerline_symbol = ""
    foreground = "black"
    background = "magenta"
### Time block properties
    [blocks.segments.properties]
      time_format = "15:05"


# Rprompt
[[blocks]]
  type = "rprompt"

# executiontime block
  [[blocks.segments]]
    type = 'executiontime'
    template = " {{ .FormattedMs }}"
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}',]
    foreground = 'yellow'

# Executiontime properties
    [blocks.segments.properties]
      threshold = 5000



# Second line
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

# Prompt
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}',]
    foreground = 'green'
    template = "{{ if .Root}}#{{ else }}❯{{ end }}"
#template = "{{ if .Root}}#{{ else }}->{{ end }}"

# Transient prompt
#[transient_prompt]
#  background = 'transparent'
#  foreground = 'green' 
#  foreground_templates = ['{{if gt .Code 0}}red{{end}}',]
#  template = "{{ if .Root}}#{{ else }}❯{{ end }}"
