general.import = [
   "~/.config/alacritty/kanagawa-wave.toml",
]
general.live_config_reload = true # set config to live reload on change

[font]  # font stuff
size = 13.0

[font.normal]
family = "Maple Mono"
style = "Medium"

[font.bold]
family = "Maple Mono"
style = "Heavy"

[font.bold_italic]
family = "Maple Mono"
style = "Heavy Italic"

[font.italic]
family = "Maple Mono"
style = "Medium Italic"

[env] # environment variables
TERM = "xterm-256color"

[window]  # transparency and stuff
# decorations = "buttonless"
dynamic_padding = false
opacity = 1
