"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[](color_orange)\
$os\
$username\
$hostname\
[ ](bg:color_orange)\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$docker_context\
[](fg:color_blue bg:color_bg3)\
$cmd_duration\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break\
$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user]($style)'

[hostname]
ssh_symbol = "@"
style = "bg:color_orange fg:bold black"
trim_at = ".zazu.no"
format = "[$ssh_symbol$hostname]($style)"

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 99
truncate_to_repo = false
truncation_symbol = ""

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
style = "bg:color_aqua fg:color_fg0"
format = '[ $symbol$branch ]($style)'

#[git_status]
#style = "bg:color_aqua fg:color_fg0"
#format = '[($all_status$ahead_behind )]($style)'

[git_status]
format = "[[(!$conflicted$untracked$modified$staged$renamed$deleted)]($style)($ahead_behind$stashed) ]($style)"
style = "bg:color_aqua fg:color_fg0"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"
ahead = ' ⇡'
diverged = ' ⇡⇣'
behind = ' ⇣'

[docker_context]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[cmd_duration]
style = "bg:color_bg3 fg:yellow"
format = "[ took ]($style fg:color_fg0)[$duration ]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

#[character]
#disabled = false
#success_symbol = '[](bold fg:color_green)'
#error_symbol = '[](bold fg:color_red)'
#vimcmd_symbol = '[](bold fg:color_green)'
#vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
#vimcmd_replace_symbol = '[](bold fg:color_purple)'
#vimcmd_visual_symbol = '[](bold fg:color_yellow)'
